// GENERATED by scripts/generate-card-art-manifest.mjs — do not edit by hand.
// Maps a card-art key (see cardArt.ts `cardArtKey`) to a bundled PNG require() id.
export const cardArtAssets: Partial<Record<string, number>> = {};
