// GENERATED by scripts/generate-card-art-manifest.mjs — do not edit by hand.
// Maps a card-art key (see cardArt.ts `cardArtKey`) to a lazy require() thunk
// for a bundled PNG (thunks keep this module import-safe under `node --test`).
export const cardArtAssets: Partial<Record<string, () => number>> = {};
